### ISSUE TITLE
Plone 5

### ISSUE THREAD

**Issue by davisagli** [plone/Products.CMFPlone#184]
This is a summary of tasks that need to be done to complete Plone 5.

It is a work in progress. In particular we need to fill in issues related to theming, mockup, plone.app.contenttypes, and new issues found via manual testing.

It is a place to reference other tickets which provide detail about particular tasks. Ideally, each task should be something that could be completed by a motivated person in a day or two. Larger efforts should be broken into smaller pieces.

Ready for review
=============

- [x] Convert portlet forms to z3c.form [#185]
- [x] Update sendto form [#94, #182]
- [x] Update author view/form [#78, #181]
- [x] Remove DLs from templates [#153]
- [x] Update default page if it is renamed [#69]
- [x] Direct user to content type migration following main site upgrade [https://github.com/plone/plone.app.contenttypes/issues/139]
- [x] Topbar design / responsive [#157]
- [x] Control panel design [#160]
- [x] modal design [#162]
- [x] ByLine design
- [x] update viewlet order in plone.app.layout [#164]
- [x] Define extra member properties TTW https://dev.plone.org/ticket/13350
- [x] Remove layout table from unstyled plone https://dev.plone.org/ticket/13358
- [x] Automatic CSRF protection https://dev.plone.org/ticket/13679
- [X] **BLOCKER** Theme editor integration @ebrehault 

To do
====

Theming
------------

- [x] Content types views design [#161]
- [x] portlet design [#163]
- [x] Logo Customization on control panel [#165] @thet
- [x] search design [#166]
- [x] contact form / sitemap design [#167]
- [X] **BLOCKER** live search [#176] @ale-rt 
- [x] Edit forms pattern
- [x] ../author/admin include floating menu on toolbar. @albertcasado to @sneridagh 
- [x] ../@@personal-preferences  include floating menu on toolbar. @albertcasado to @sneridagh 
- [x] Integrate theme styles on Tiny MCE. for @bloodbare 
- [x] Manage viewlets view [#625]

Javascript (Mockup)
-------------------------

- [x] [#279] convert plone.app.contentrules javascript to mockup pattern, [contentrule-elements.js](https://github.com/plone/plone.app.contentrules/blob/master/plone/app/contentrules/browser/contentrule-elements.js) - STATUS: Chrissy to review status
- [X] [https://github.com/plone/mockup/issues/434] add a pat-eventedit class to the body or form of the edit form of an event - OWNER: Johannes 
- [X] [#282] Create tickets for each of the remaining scripts in plone_ecmascript - OWNER: Johannes + JC
- [x] [#281] Make sure correct widgets from plone.app.widgets are used for dublin core fields - STATUS: complete
- [x] [#280] Move plone.app.widgets code and test to CMFPlone/plone.app packages - ON HOLD - OWNER: Nathan
- [x] Modal css on barceloneta theme - STATUS: Albert to confirm it's done. Albert: I confirm
- [X] [https://github.com/plone/mockup/issues/414] do not allow building bundles if has unsaved changes - STATUS: Nathan to add details
- [x] [https://github.com/plone/mockup/issues/435] Update Mockup documentation - OWNER: Chrissy
- [x] [https://github.com/plone/mockup/issues/413] Folder contents css not working  - OWNER: Chrissy - Fix committed 
- [X] [https://github.com/plone/mockup/issues/451] Recurrence pattern.
- [X] [https://github.com/plone/Products.CMFPlone/issues/289] TinyMCE control panel settings are not fully implemented

Migration
------------

- [x] Documentation: how to migrate schema extender fields
- [x] Documentation: how to migrate custom content types
- [x] Migration of Custom Types (https://github.com/plone/plone.app.contenttypes/issues/133)
- [ ] **BLOCKER** Registry migration (from Resource Registry)

Member-related (will be focus of Emerald Sprint)
---------------------

- [ ] Convert login forms to z3c.form [#105]
- [x] Convert password reset forms to z3c.form [#87, #127]
- [x] Update member preferences templates [#88]
- [ ] Remove portal_registration [#126]

Cleanup
-----------

- [x] **BLOCKER** Move filter control panel to z3c.form. [#211] @tisto
- [x] Move user prefs control panel to z3c.form. [#212] @tisto
- [x] **BLOCKER** Move editing control panel to z3c.form. [#213] @tisto
- [x] **BLOCKER** Move mail control panel to z3c.form. [#214] @tisto
- [x] **BLOCKER** Move navigation control panel to z3c.form. [#215]
- [x] **BLOCKER** Move security control panel to z3c.form. [#216] @tisto
- [x] Move types control panel to z3c.form. [#217]
- [x] **BLOCKER** Move language control panel to z3c.form. [#218] @tisto
- [x] Move maintenance control panel to z3c.form. [#219]
- [x] **BLOCKER** Move markup control panel to z3c.form. [#220] @tisto
- [x] Move usergroup control panel to z3c.form. [#221]
- [x] Move the control panel overview Products.CMFPlone [#290]
- [x] Move the ram controlpanel into CMFPlone [#361]
- [ ] Move the permission definitions from p.a.controlpanel into Products.CMFPlone [#291]
- [ ] Check all plone.app.controlpanel master commits since f98f6c (last communal commit between master and plip10359-z3cform) and cherry-pick the needed ones. 
- [ ] Go through all z3c.form tickets and make sure they have been finished.
- [x] Convert "Delete Confirmation" to a browser view [#84]
- [x] Remove old AT content views [#80]
- [x] Save default page -> browser view [#90]
- [x] Select view template -> browser view in p.a.content [#91]
- [x] Migrate site feedback to z3c.forms [#92]
- [x] Migrate Rename [#97]
- [x] Copy/Cut/Paste/Delete [#97]
- [x] Migrate history views [#100]
- [ ] Remove portal_migration tool [#128]
- [ ] merge some `plone.app.*` packages into the `Products.CMFPlone` distribution [#28]
- [x] Get rid of Products.PloneTestCase for plone core packages. [#222] 
- [ ]  Fix plone.app.versioningbehavior test problems. [#223] 
- [x] Move plone.app.viewletmanager to plone.app.testing [#240]
- [x] Remove Products.TinyMCE
- [ ] Remove Products.ResourceRegistry
- [ ] Remove portal_skins from Products.CMFPlone https://dev.plone.org/ticket/13260

Misc
------

- [x] **BLOCKER** plone.app.multilingual https://dev.plone.org/ticket/13091 @bloodbare 
- [x] Collections: folderish plus migration from Topic to Collection https://dev.plone.org/ticket/13561
- [x] Use lxml cleaner for safehtml transforms https://dev.plone.org/ticket/14929

Bugs
-------

- [x] **BLOCKER** Linkintegrity is broken in Plone 5 [#255, #698] @pbauer 
- [x] **BLOCKER** KeyError: 'plone.resources.development' https://dev.plone.org/ticket/20133
- [ ] Portlet headings should include heading tags for accessibility https://dev.plone.org/ticket/11978
- [ ] **BLOCKER** Access to acquired content should not be allowed https://dev.plone.org/ticket/13793
- [ ] Python is built without bz2 if `libbz2-dev` is not installed https://dev.plone.org/ticket/13819
- [x] **BLOCKER** Sharing https://dev.plone.org/ticket/14192
- [x] User and Group Control Panel https://dev.plone.org/ticket/14197
- [x] **BLOCKER** syndication settings: JS error https://dev.plone.org/ticket/14276
- [x] **BLOCKER** Deleting an item returns a 404 https://dev.plone.org/ticket/14463
- [x] Quickinstaller does not show CMFPlacefulWorkflow and plone.app.iterate #342 

Note: tasks considered blockers for a Plone 5 beta release are marked as **BLOCKER**

**Comment by vincentfretin** [comment]
We need some love on i18n, I created a separate issue with all the i18n issues I found in november:
https://github.com/plone/Products.CMFPlone/issues/379

**Comment by vangheem** [comment]
Definitely. It'd be good if someone went through all the javascript and made sure i18n wrappers were used everywhere there is text also.

**Comment by jensens** [comment]
Plone 5 is released. I close this one.

**Comment by gforcada** [comment]
:tada:

**Comment by hvelarde** [comment]
yes, Plone 5 is relased but there are some important issues that MUST be fixed and we need to keep an eye on them.

one item needs special attention:

* **BLOCKER** Registry migration (from Resource Registry) (no issue)

also note that these ones need huge deprecation warnings on Plone 4 and Plone 5:

* Remove Products.ResourceRegistry (no issue, neither)
* Remove portal_skins from Products.CMFPlone https://dev.plone.org/ticket/13260

**Comment by gforcada** [comment]
@hvelarde create issues for all of them and add milestone 5.0.x on them, this one was a tracker for 5.0 which is out.

**Comment by hvelarde** [comment]
done!

* Registry migration (from Resource Registry) (#1224)
* Remove Products.ResourceRegistry (#1225)

**Comment by jensens** [comment]
Thanks!
