### ISSUE TITLE
ToDo list for Barceloneta Theme - PLOG2014

### ISSUE THREAD

**Issue by sneridagh** [plone/Products.CMFPlone#207]
This is the to-do list identified (and addressed if checked) at Plog 2014 by @albertcasado, @bloodbare and @sneridagh
- [ ]  Modal/Structure pattern (folder contents) empty footer on modals
- [ ]  Remove/make invisible empty yellow "alert" between menus and table on folder contents 
- [ ]  Folder contents: on burger-menu title check makes title appear duplicate on the table, remove from burger-menu
- [ ] Remove/change the burger-icon for the check options because this is not a menu
- [ ]  Folder contents with long list of items on the table makes impossible to access bottom contents because modal has a fixed height. We need to add scroll on the modal-body or remove e modal on that
- [ ] Sharing has he same problem (as previous check) if the list of users is long the modal does not scroll.
- [ ]  Edit default view of a container shows info portal-message in a DL>DT+DD
- [ ]  Sharing shows info portal-message in a DL>DT+DD
- [ ]  Sitemap menu (other menus are exactly the same) generates a LI>DIV>A>SPAN. We just need to keep LI>A. The DIV is an old trick for IE6 and the SPAN I think is dependant of the i18n or someting but must be out to have a clear code.
- [ ] Update access keys (follow UK gov. recomendation: http://webarchive.nationalarchives.gov.uk/20100807034701/http://archive.cabinetoffice.gov.uk/e-government/resources/handbook/html/2-4.asp)
- [ ] Remove accessibility text size (large/medium/small) or make that JS works. That's an old-school accessibility issue I think we can remove.
- [ ] Contact-info is on a modal. Is it ok?
- [ ] exclude_from_nav bool widget is rendering as "required" when obviously it's not. p.a.contenttypes is not marking it as required, so it's a wide issue for all bools widgets?
- [ ] Related Items widget is not working so we can't fix its CSS
- [ ] Bootstrap-group button and input search widgets
- [ ]  Event template with DL>DT+DD need to be changed to UL>LI
- [ ] Create element from folder contents do not refresh de page on the background and it is so confusing
- [ ] News element: Markuped as article instead of a section.
- [ ] File element: mess of code. Clean it
- [ ] Viewlet above content and below: Must disappear if empty (it appears on link element and file element)

**Comment by vangheem** [comment]
I'm closing this because it just doesn't seem valid anymore. Reopen is you'd like.

**Comment by tkimnguyen** [comment]
@polyester there are some accessibility-related items in this checklist

**Comment by djay** [comment]
Contact-info shouldn't be a model IMO
