### ISSUE TITLE
Start migrating Plone to Python 3

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2217]
# Meta-ticket to collect todos for this task. 

Initial work was documented in https://docs.google.com/document/d/1rYN817-9SjAQulpes36k1veTt4pABZRbl0T0BbuZrHA/edit# 

## Tasks
* [ ] Document setup of different Python 3 versions, tox and related tools to test and maintain Python 3 compatibility.
* [ ] Migrate GenericSetup and MailHost to Python 3 (Godefroid Chapelle and Andreas Zeidler)
* [X] Update the jenkins-job for python3 (http://jenkins.plone.org/view/py3)
* [ ] Migrate packages without CMFPlone dependencies (e.g. finish migration of plone.rfc822)
* [ ] Fix all import-errors everywhere (use 2to3 and six to create backwards-compatible imports)
* [ ] Look at plone.testing and plone.app.testing if we can get the lowermost testlayers to start on python 3

## Pull-requests to fix imports with Python 3
* [ ] AccessControl [@rudaporto] - https://github.com/zopefoundation/AccessControl/pull/48
* [ ] plone.api [@rudaporto] - https://github.com/plone/plone.api/pull/394
* [ ] plone.app.blob [@rudaporto] - 
* [ ] plone.app.caching [@b4oshany] - https://github.com/plone/plone.app.caching/pull/40 
* [ ] plone.app.collection [@rudaporto] - nothing to do
* [ ] plone.app.content [@ale-rt] - plone.app.content/pull/143
* [ ] plone.app.contentlisting [@rudaporto] - nothing to do
* [ ] plone.app.imaging [@ale-rt] - https://github.com/plone/plone.app.imaging/pull/34
* [ ] plone.app.layout [@ale-rt] - https://github.com/plone/plone.app.layout/pull/134
* [ ] plone.app.ldap [ale-@rt] - https://github.com/plone/plone.app.ldap/pull/33
* [ ] plone.app.linkintegrity - [ale-rt] https://github.com/plone/plone.app.linkintegrity/pull/61
* [ ] plone.app.locales [@rudaporto] - nothing to do
* [ ] plone.app.mosaic [@b4oshany] - https://github.com/plone/plone.app.mosaic/pull/390 
* [ ] plone.app.multilingual [@ale-rt] - https://github.com/plone/plone.app.multilingual/pull/296 
* [ ] plone.app.openid [@b4oshany] - https://github.com/plone/plone.app.openid/pull/12 
* [ ] plone.app.portlets [@ale-rt] - https://github.com/plone/plone.app.portlets/pull/104
* [ ] plone.app.relationfield [@rudaporto] - nothing to do
* [ ] plone.app.robotframework [ale-rt, @b4oshany] - https://github.com/plone/plone.app.robotframework/pull/70    
* [ ] plone.app.standardtiles [@b4oshany] - https://github.com/plone/plone.app.standardtiles/pull/82 
* [ ] plone.app.testing [@rudaporto] - nothing to do
* [ ] Plone.app.textfield [@b4oshany] - https://github.com/plone/plone.app.textfield/pull/26 
* [ ] plone.app.theming https://github.com/plone/plone.app.theming/pull/137
* [ ] plone.app.upgrade [@rudaporto] - nothing to do
* [ ] plone.app.users [@rudaporto] - nothing to do
* [ ] Plone.app.versioningbehavior - https://github.com/plone/plone.app.versioningbehavior/pull/35
* [ ] plone.app.workflow [@rudaporto] - nothing to do
* [ ] plone.app.z3cform https://github.com/plone/plone.app.z3cform/pull/80
* [ ] plone.autoform [@rudaporto] - nothing to do
* [ ] plone.behavior [@rudaporto] - nothing to do
* [ ] plone.dexterity [@pbauer] - https://github.com/plone/plone.dexterity/pull/74 
* [ ] plone.formwidget.namedfile - [ale-@rt] - https://github.com/plone/plone.formwidget.namedfile/pull/30
* [ ] plone.intelligenttext - nothing to do
* [ ] plone.namedfile [@ale-rt] - https://github.com/plone/plone.namedfile/pull/60
* [ ] plone.supermodel [@b4oshany] - https://github.com/plone/plone.supermodel/pull/23
* [ ] plone.testing - https://github.com/plone/plone.testing/pull/38 
* [ ] plone.uuid - nothing to do
* [ ] Products.CMFCore [@rudaporto] - https://github.com/zopefoundation/Products.CMFCore/pull/29
* [ ] Products.CMFFormController [@rudaporto] - https://github.com/plone/Products.CMFFormController/pull/13
* [ ] Products.CMFPlone [@pbauer] - https://github.com/plone/Products.CMFPlone/pull/2181 
* [ ] Products.i18ntestcase [@b4oshany] - https://github.com/plone/Products.i18ntestcase/pull/1 
* [ ] Products.PlonePAS [@pbauer] - https://github.com/plone/Products.PlonePAS/pull/26 
* [ ] Products.PluggableAuthService [@rudaporto] - https://github.com/zopefoundation/Products.PluggableAuthService/pull/10
* [ ] Products.ZopeVersionControl [@rudaporto] - https://github.com/zopefoundation/Products.ZopeVersionControl/pull/1

**Comment by ale-rt** [comment]
Take care that many of that PR use the `_compat` module approach instead of sixer.
We should not merge them as they are, see:

- https://github.com/plone/Products.CMFPlone/pull/2181

**Comment by pbauer** [comment]
Packages that still need to be looked at for this ticket: https://oasis.sandstorm.io/shared/Rw17tl3FBnXpwgqO-6-86UxGYYuPD8jyW40oPhAnvRs

**Comment by pbauer** [comment]
Some pull-requests need to replace replace `_compat` with `six`:

* [ ] https://github.com/plone/plone.app.imaging/pull/34
* [ ] https://github.com/plone/plone.app.linkintegrity/pull/61

Please update this list when you encounter any.

**Comment by andreasma** [comment]
I worked on the package cioppino.twothumbs and updated it locally with sixer and python-modernize and some fixes of imports. The package works in my local environment. I tried to test my pull request for python 2 to 3 with Travis-CI, but I can't get Travis to work. I need some hints how I could fix this. My current work is available here: https://github.com/collective/cioppino.twothumbs/pull/23 (I used branch python3 inside my own fork).
