### ISSUE TITLE
TRACKER: test isolation problems

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#2290]
*Copied over from https://github.com/plone/buildout.coredev/pull/155:*

Mixing ``ZopeTestCase`` and ``plone.app.testing`` **within** the same distribution renders all its tests unstable with newer versions of ``zope.testrunner``.

Note that fixing these test isolation problems not only has the benefit of having more robust tests, but at the same time our test infrastructure will be way more easy (and with that making it far easier to reproduce bugs that are only triggered in Jenkins).

Another nice bonus is that unit tests will run first and thus early feedback if you are already expecting failures.

Lastly a slight increase on speed, due to less layer setup and teardown should be observed as well.

The list of packages affected are:

_please create separate tickets for each of them and link them back here so we can keep track of it_

**Archetypes ecosystem**
- [ ] archetypes.multilingual
- [ ] plone.app.blob
- [ ] Products.Archetypes
- [ ] Products.ATContentTypes
- [ ] Products.Marshall
- [ ] plone.app.folder

**Other**
- [x] plone.app.content [#152](https://github.com/plone/plone.app.content/pull/152)
- [ ] plone.app.portlets
- [ ] plone.session
- [ ] Products.ExternalEditor
- [ ] Products.GenericSetup
- [ ] Products.CMFCore
- [ ] Products.CMFEditions
- [x] Products.CMFPlacefulWorkflow [#20](https://github.com/plone/Products.CMFPlacefulWorkflow/pull/20)
- [ ] Products.CMFPlone [#1348](https://github.com/plone/Products.CMFPlone/issues/1348)
- [ ] Products.CMFUid
- [ ] Products.PluggableAuthService
- [ ] Products.Sessions

**Comment by jensens** [comment]
I think we fixed all of these. Reopen if I am wrong.

**Comment by gforcada** [comment]
Unfortunately not, it is not done yet, a few `Products.*` distributions do still use it, but that's beyond the scope here, and the real one that does need fixing is [plone/schemaeditor/tests/tests.py](https://github.com/plone/plone.schemaeditor/blob/master/plone/schemaeditor/tests/tests.py#L3).

I swear I did try multiple times to remove it and replace it with `plone.(app.)testing` but ... 😵‍💫 it's too much for me 🤷🏾 

Anyone wants to be my hero-for-life? 🍀 😄

**Comment by gforcada** [comment]
`plone.schemaeditor` is still black magic to me: somehow it made it to Python 3 still with `ZopeTestCase` on it 🤷🏾 😅

**Comment by jensens** [comment]
Closing as outdated (5 years old). Test isolation tracker from 2018. Only plone.schemaeditor remains and should be tracked in that repo.
If you think this issue is still relevant please reopen it. Thank you for the original report!
