### ISSUE TITLE
Change Templates to Bootstrap Markup

### ISSUE THREAD

**Issue by santonelli** [plone/Products.CMFPlone#2967]
## Abstract

Use Bootstrap HTML markup in all templates used in Plone core and Plone's ecosystem (packages, widgets, etc.)

There will be another PLIP to add a all new theme for Plone 6 based on this work.

## Motivation

Everybody who wants to build a theme based on Bootstrap for Plone has to deal with more or less useful HTML markup injected by packages, widgets, plugins, patterns, etc.

## Assumptions

* We keep Barceloneta for the moment
* Changes should not break Barceloneta
* Barceloneta can override incompatible markup

### Affected Templates

- [ ] Issue #3079 Control panel templates in Products.CMFPlone
- [x] Issue #3080 Login templates in Products.CMFPlone
- [ ] Issue #3081 Other templates in Products.CMFPlone
- [ ] https://github.com/plone/plone.app.content/issues/196
- [x] https://github.com/plone/plone.app.contentrules/issues/53
- [x] https://github.com/plone/plone.app.contenttypes/issues/548
- [ ] https://github.com/plone/plone.app.dexterity/issues/318
- [ ] https://github.com/plone/plone.app.caching/issues/63
- [ ] https://github.com/plone/plone.app.discussion/issues/169
- [ ] https://github.com/plone/plone.app.event/issues/315
- [x] https://github.com/plone/plone.app.layout/issues/235
- [ ] https://github.com/plone/plone.app.mosaic/issues/473
- [x] https://github.com/plone/plone.app.multilingual/issues/379
- [x] https://github.com/plone/plone.app.portlets/issues/137
- [x] https://github.com/plone/plone.app.registry/issues/43
- [x] https://github.com/plone/plone.app.users/issues/96
- [x] https://github.com/plone/plone.app.workflow/issues/24
- [x] https://github.com/plone/plone.app.z3cform/issues/113
- [x] https://github.com/plone/plone.batching/issues/25
- [x] https://github.com/plone/plone.portlet.collection/issues/24
- [x] https://github.com/plone/plone.portlet.static/issues/20
- [ ] https://github.com/plone/plone.schemaeditor/issues/82
- [x] https://github.com/plone/plone.staticresources/issues/114
- [x] https://github.com/plone/plone.z3cform/issues/15
- [x] https://github.com/plone/plonetheme.barceloneta/issues/225

### Views with unknown template

- ~plone_upgrade~ (Products.CMFPlone)
- ~folder_contents~ (very complex structure pattern in plone.app.content)
- ~edit~ (edit views via z3cform)
- ~prefs_install_products_form~ (Add-ons controlpanel)
- ~redirection-controlpanel~
- ~manage-viewlets~
- ~manage-portlets~
- ~sharing~
- ~personal-information~ (plone.app.users)
- ~maintenance-controlpanel~  (done in controlpanel subissue #3079)

#### Coredev buildout

```
git clone git@github.com:plone/buildout.coredev.git plone-6-coredev
cd plone-6-coredev
git checkout 6.0
python3.7 -m venv py
./py/bin/pip install -r requirements.txt
./py/bin/buildout -c plips/plip-2967-barceloneta-lts.cfg
./bin/instance fg
```
Identify an element that needs to be updated
- Create a branch in the package where the template comes from
- Update/Change markup to Bootstrap
- Push your branch
- Create a Pull Request 

##### Requirements

- You need Node on your system
- Best practice is to use NVM for that
- Installation & Instructions
- OSX https://www.wdiaz.org/how-to-install-nvm-with-homebrew/
- Linux https://nodesource.com/blog/installing-node-js-tutorial-using-nvm-on-mac-os-x-and-ubuntu/
- General information about build tools in Bootstrap https://v5.getbootstrap.com/docs/5.0/getting-started/build-tools/

##### Compile 
- cd src/plonetheme.barceloneta
- yarn install (instal dependencies)
- yarn watch (watch for changes in sass files, type rs to restart compilation)

##### Hint

- Do not add compiled CSS to your merge request (we do this on the main branch after merge)

#### Markup Update/Change hints

- Wherever possible use Bootstrap components (https://v5.getbootstrap.com/docs/5.0/components/alerts/)
- It's not important to copy Plone 5 design
- Try to re-think how a piece of Plone could be done with plain Bootstrap (see already existing breadcrumbs as example)
- Check plonetheme.tokyo for already existing templates (https://github.com/collective/plonetheme.tokyo)
- Before we use Utilities/Spacing (e.g. https://v5.getbootstrap.com/docs/5.0/utilities/spacing/) for specific components check if this should go to a global css

## Deliverables

TBD

## Risks

Plone's default theme Barceloneta may break at some point. Default classes should not hurt if there is no styling for it.

## Participants

* Stefan Antonelli
* Peter Holzer

**Comment by ebrehault** [comment]
This PLIP has been approved by the FWT

**Comment by pbauer** [comment]
Radiobuttons are not yet styled correctly.

I used https://github.com/collective/example.contenttype to render all field types.

![dx_fields](https://user-images.githubusercontent.com/453208/97017472-3f62bd00-154e-11eb-8e46-d11b53b6d982.png)

**Comment by agitator** [comment]
@pbauer radios should be fixed now

**Comment by jensens** [comment]
Sharing template needs love as well.

**Comment by agitator** [comment]
Updated PLIP for Bootstrap 5

**Comment by MrTango** [comment]
We should update the breadcrumbs a bit to be more compatible with W3C ideas: https://github.com/plone/Products.CMFPlone/issues/3262

**Comment by agitator** [comment]
The plip config is no longer needed, all package branches were merged in to buildout.coredev 6.
Continuation of improvements should happen in the actual package.
