### ISSUE TITLE
Known i18n issues on Plone 5.2

### ISSUE THREAD

**Issue by vincentfretin** [plone/Products.CMFPlone#3123]
Here a list of known i18n issues on Plone 5.2:

- [ ] https://github.com/plone/Products.CMFPlone/issues/3120 Issues in richtext editor
- [ ] https://github.com/plone/Products.CMFPlone/issues/2953 Issues with i18n of "last modified" dates format
- [ ] https://github.com/plone/Products.CMFPlone/issues/2188 Translations in folder_contents are incomplete

**Comment by vincentfretin** [comment]
For the first three issues, all the issues are in mockup.
I started some doc at https://github.com/plone/mockup/pull/985 if you want to help fixing those.

**Comment by erral** [comment]
I would add this to keep-it under the radar: https://github.com/plone/plone.app.linkintegrity/issues/76

**Comment by jensens** [comment]
Closing as outdated (6 years old). Meta-tracking issue for Plone 5.2.2 i18n. Most items checked off. Individual issues stand on their own.
If you think this issue is still relevant please reopen it. Thank you for the original report!
