### ISSUE TITLE
Plone 4.3.20 release checklist

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#3166]
Release checklist for Plone 4.3.20. This is the final release of 4.3.x. Let's make it a smooth one.
See also the [release schedule](https://plone.org/download/release-schedule).

This list is mostly for me as release manager, but feel free to tag an issue as blocker, and link it here in a comment, or add other checklist items or questions/suggestions.

Tag on coredev: https://github.com/plone/buildout.coredev/tree/4.3.20

Here is the checklist, based on https://docs.plone.org/develop/coredev/docs/release.html (see [source](https://github.com/plone/buildout.coredev/blob/5.2/docs/release.rst)), but really just a copy of https://github.com/plone/Products.CMFPlone/issues/3119:

- [x] Check Jenkins Status: should be green. (This should be checked often during the release process.)
- [x] In coredev, check packages for updates: `bin/manage report --interactive`
- [x] Release individual packages from `checkouts.cfg`.
- [x] Check that the version numbers of [`CMFPlone metadata.xml`](https://github.com/plone/Products.CMFPlone/blob/4.3.x/Products/CMFPlone/profiles/default/metadata.xml) and latest [`upgrade step`](https://github.com/plone/plone.app.upgrade/blob/1.x/plone/app/upgrade/v43/configure.zcml) are in sync. The version number must be higher than from the previous Plone release, otherwise @@plone-upgrade will not do anything, and we may miss upgrades from some core add-ons.
- [x] If unsure, ask if `mockup` and `plone.staticresources` are in sync and can be released. [irrelevant for 4.3]
- [x] If needed, [ask the Plone REST api team](https://github.com/plone/plone.restapi/issues) for a new release of `plone.restapi` and `plone.rest`. [irrelevant for 4.3]
- [x] Write an email to the translation team, asking them to do a plone.app.locales release. Or create an issue in https://github.com/collective/plone.app.locales/issues
- [x] Update `plone.app.locales` version.
- [x] Create a pending release (directory) on dist.plone.org
  - [x] Copy all core packages there. TODO: is there a handy command for this?
  - [x] Possibly make an alpha/beta release of `Products.CMFPlone` and put it only on dist.plone.org, not PyPI.
  - [x] Copy files from coredev there: `versions.cfg`, `requirements.txt`. Plus `constraints.txt` and `RELEASE-NOTES.txt` if you have it.
- [x] Create a unified changelog: `bin/manage changelog`
- [x] Write a post on community.plone.org announcing a pending/soft release. See [example](https://community.plone.org/t/plone-5-2-1-soft-released/11098)
- [x] Wait for feedback, preferably at most a few days.
- [x] Make final release of `Products.CMFPlone` to PyPI
- [x] Make final release on dist.plone.org (remove "-pending", make sure updated distributions are added).
- [x] Update the "-latest" link on dist.plone.org
- [x] Create new release on launchpad (https://launchpad.net/plone/): `bin/manage launchpad <version>`
- [x] Create release page on https://plone.org/download/releases
- [x] Announce community.plone.org, with warning that installers are not ready yet.
- [x] Send links to [installers list](mailto:plone-installers@lists.sourceforge.net)
- [ ] Wait for installers to be uploaded to Launchpad, link on plone.org release page
- [x] Publish release page on plone.org
- [x] Update plone.org homepage links to point to new release
- [ ] Send out announcement to plone-announce
- [ ] Update #plone irc channel topic
- [x] Ask the security team to update the https://plone.org/security/hotfixes/ page in the configuration control panel. (Configuration registry: `plone.securitysupport`, `plone.versions`, `plone.activemaintenance`)
