### ISSUE TITLE
Release checklist Plone 5.2.3

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#3199]
See the [release schedule](https://plone.org/download/release-schedule).

- [x] Check Jenkins Status: should be green. (This should be checked often during the release process.)
- [x] In coredev, check packages for updates: `bin/manage report --interactive`
- [x] Release individual packages from `checkouts.cfg`.
- [x] Check that the version numbers of [`CMFPlone metadata.xml`](https://github.com/plone/Products.CMFPlone/blob/5.2.x/Products/CMFPlone/profiles/default/metadata.xml) and latest [`upgrade step`](https://github.com/plone/plone.app.upgrade/blob/master/plone/app/upgrade/v52/configure.zcml) are in sync.
- [x] If unsure, ask if `mockup` and `plone.staticresources` are in sync and can be released. https://github.com/plone/mockup/issues/1026
- [x] If needed, [ask the Plone REST api team](https://github.com/plone/plone.restapi/issues) for a new release of `plone.restapi` and `plone.rest`.
- [x] Write an email to the translation team, asking them to do a plone.app.locales release. Or create an issue in https://github.com/collective/plone.app.locales/issues
- [x] Update `plone.app.locales` version.
- [x] Create a pending release (directory) on dist.plone.org
  - [x] Copy all core packages there. TODO: is there a handy command for this?
  - [x] Possibly make an alpha/beta release of `Products.CMFPlone` and put it only on dist.plone.org, not PyPI.
  - [x] Copy the versions.cfg file from coredev there.
- [x] Create a unified changelog: `bin/manage changelog`
- [x] Write a post on community.plone.org announcing a pending/soft release. See [example](https://community.plone.org/t/plone-5-2-1-soft-released/11098)
- [x] Wait for feedback, preferably at most a few days.
- [x] Make final release of `Products.CMFPlone` to PyPI
- [x] Make final release on dist.plone.org (remove "-pending", make sure updated distributions are added).
- [x] Update the "-latest" link on dist.plone.org
- [x] Create new release on launchpad (https://launchpad.net/plone/): `bin/manage launchpad <version>`
- [x] Create release page on https://plone.org/download/releases
- [x] Announce community.plone.org, with warning that installers are not ready yet.
- [x] Send links to [installers list](mailto:plone-installers@lists.sourceforge.net)
- [ ] Wait for installers to be uploaded to Launchpad, link on plone.org release page
- [x] Publish release page on plone.org
- [x] Update plone.org homepage links to point to new release. Or really: https://plone.org/download
- [ ] Send out announcement to plone-announce
- [ ] Update #plone irc channel topic
- [x] Ask the security team to update the https://plone.org/security/hotfixes/ page in the configuration control panel. (Configuration registry: `plone.securitysupport`, `plone.versions`, `plone.activemaintenance`)

**Comment by mauritsvanrees** [comment]
First thing that should be arranged now is to have a `mockup` and `plone.staticresources` release without breaking changes. See https://github.com/plone/mockup/issues/1026. We likely need to make branches for those.

**Comment by mauritsvanrees** [comment]
Main blocker: my wife will be having a baby tomorrow (or today if the little one is fast). :-)
Don't expect more Plone work from me this week. :-D

**Comment by fredvd** [comment]
Not to spoil the release, but this bug in the folder_contents is really nasty and dangerous when editors do content actions on the wrong content items. I'd consider this a blocker: https://github.com/plone/Products.CMFPlone/issues/3191

**Comment by mauritsvanrees** [comment]
I have soft released 5.2.3. See [community](https://community.plone.org/t/plone-5-2-3-soft-released/13065) announcement.

Branch is here: https://github.com/plone/buildout.coredev/tree/release-5.2.3-pending
I should probably be the only one committing there directly.

**Comment by mauritsvanrees** [comment]
There have been new releases of Zope and several other packages. I have added [comments on community](https://community.plone.org/t/plone-5-2-3-soft-released/13065/10?u=mauritsvanrees). I expect we have a green light today or tomorrow.
