### ISSUE TITLE
Release checklist Plone 5.2.4

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#3250]
See the [release schedule](https://plone.org/download/release-schedule).

- [x] Check Jenkins Status: should be green. (This should be checked often during the release process.)
- [x] In coredev, check packages for updates: `bin/manage report --interactive`
- [x] Release individual packages from `checkouts.cfg`.
- [x] Check that the version numbers of [`CMFPlone metadata.xml`](https://github.com/plone/Products.CMFPlone/blob/5.2.x/Products/CMFPlone/profiles/default/metadata.xml) and latest [`upgrade step`](https://github.com/plone/plone.app.upgrade/blob/master/plone/app/upgrade/v52/configure.zcml) are in sync.
- [x] If unsure, ask if `mockup` and `plone.staticresources` are in sync and can be released. Example: https://github.com/plone/mockup/issues/1026
- [x] If needed, [ask the Plone REST api team](https://github.com/plone/plone.restapi/issues) for a new release of `plone.restapi` and `plone.rest`.
- [x] Write an email to the translation team, asking them to do a plone.app.locales release. Or create an issue in https://github.com/collective/plone.app.locales/issues
- [x] Update the versions of those packages.
- [x] Make an release candidate release of `Products.CMFPlone` (e.g. 5.2.4rc1). Fine to release this on PyPI.
- [x] Create a coredev branch, `prepare-524`. Empty the `auto-checkout` list in `checkouts.cfg`.
- [x] Create a pending release (directory) on dist.plone.org, e.g. 5.2.4-pending, and gather files to put there:
  - [x] Create a unified changelog: `bin/manage changelog --start=5.2.X > changelog.txt`. Remove the uninteresting top lines.
  - [x] Create a `RELEASE-NOTES.txt`. It may be enough to look through the changelog and copy interesting changes.
  - [x] Gather all package distributions.
        You can use `tox -c release/tox.ini -p auto` to gather them in `release/dist`, together with a few other files.
  - [x] Get the versions.cfg file from coredev.
  - [x] Create a `constraints.txt` from this. The above tox command generates this and puts it in `release/dist`.
  - [x] Copy (`rsync`) all core packages and the other files to the pending release directory. I think we mostly do this so we have a backup if a version gets removed from PyPI.
- [x] Write a post on community.plone.org announcing a pending/soft release. See [example](https://community.plone.org/t/plone-5-2-4-soft-released/13495)
- [x] Wait for feedback, preferably at most a few days.
- [x] Make final release of `Products.CMFPlone` to PyPI, update `versions.cfg`.
- [x] Create tag of the release branch, e.g. 5.2.4, and push to GitHub.
- [x] Make final release on dist.plone.org (remove "-pending", make sure updated distributions, versions and constraints are added).
- [x] Update the "-latest" link on dist.plone.org
- [x] Create new release on launchpad (https://launchpad.net/plone/): `bin/manage launchpad <version>`
- [x] Create release page on https://plone.org/download/releases
- [x] Announce community.plone.org, with warning that installers are not ready yet. Or ask Marketing team, also see below.
- [x] Send links to [installers list](mailto:plone-installers@lists.sourceforge.net), or create an issue, like [this one](https://github.com/plone/Installers-UnifiedInstaller/issues/112)
- [x] Wait for installers to be uploaded to Launchpad, link on plone.org release page
- [x] Publish release page on plone.org. If the installer takes too long, publish it anyway. Coordinate with the Marketing Team.
- [x] Marketing Team: Send out announcement to plone-announce, Twitter, update #plone irc channel topic, what you want.
- [x] Ask the security team to update the https://plone.org/security/hotfixes/ page in the configuration control panel. (Configuration registry: `plone.securitysupport`, `plone.versions`, `plone.activemaintenance`)

**Comment by mauritsvanrees** [comment]
Blocker is now a few security related changes in Zope, GenericSetup and QuickInstaller.

**Comment by mauritsvanrees** [comment]
Blocker is handled. Release should be there tomorrow.
