### ISSUE TITLE
Release checklist Plone 6.0.1

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#3716]
See the [release schedule](https://plone.org/download/release-schedule).

## Release packages, update versions

- [x] Check Jenkins Status: should be green. (This should be checked often during the release process.)
- [x] In coredev, check packages for updates: `bin/manage report --interactive`. This is less needed now that we have `mr.roboto` to add packages to the checkouts.  Use `bin/versioncheck` to see if any new PyPI releases are worth adding, or check the artifact of the [versioncheck GitHub Action](https://github.com/plone/buildout.coredev/actions/workflows/versioncheck.yml).
- [x] Release individual packages from `checkouts.cfg`.
- [x] Check that the version numbers of [`CMFPlone metadata.xml`](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/profiles/default/metadata.xml) and latest [`upgrade step`](https://github.com/plone/plone.app.upgrade/blob/master/plone/app/upgrade/v60/configure.zcml) are in sync, and that they are higher than in the previous Plone release.
- [x] Handle special packages, often handled by special people. :-) You can can ping people in the release-team channel on Discord, in the current issue, or individually:
  - [x] [plonetheme.barceloneta](https://github.com/plone/plonetheme.barceloneta) needs a release on PyPI and npmjs. Maybe ask Peter Holzer (agitator) or Peter Mathis (petschki) for assistence.
  - [x] [`plone.staticresources`](https://github.com/plone/plone.staticresources) and [`mockup`](https://github.com/plone/mockup). Ask on Discord in the classic-ui or ask Johannes (thet), Peter Mathis (petschki) or Maik (MrTango).
  - [x] `plone.restapi` and maybe `plone.volto`. If needed, [ask the Plone REST api team](https://github.com/plone/plone.restapi/issues) or Timo (tisto) for a new release.
  - [x] [`plone.app.locales`](https://github.com/collective/plone.app.locales). Create an issue there or ask Mikel (erral).
  - [x] Release `plone.app.upgrade` and `Plone` yourself.
  - [x] Update the versions of those packages in `versions.cfg`.
- [x] Make an alpha/beta/release candidate release of `Products.CMFPlone` (e.g. 6.0.0a1, later 6.0.0b1 and 6.0.0rc1). Fine to release this on PyPI.  Once Plone 6 is final, we can continue doing release candidates for the bugfix releases, so people can try it in a pending release.

## Release notes, constraints, dist.plone.org

- [x] Adjust coredev branch [`release/6.0-dev`](https://github.com/plone/buildout.coredev/tree/release/6.0-dev). Most importantly, the `auto-checkout` list in `checkouts.cfg` should be empty, and the `versions.cfg` and `requirements.txt` should be the same.  One way that works for me: `git checkout release/6.0-dev; git reset --hard 6.0; git reset origin/release/6.0-dev`.  Then check which changes you want to commit.
- [x] Update the `6.0-dev` directory on dist.plone.org, and gather files to put there:
  - [x] You can use `tox -c release/tox.ini -p auto` to create or copy some files in `release/dist`.  But you need to create some of those files first.
  - [x] Create a unified changelog based on the previous release: `bin/manage changelog --start=6.0.0a1 > release/changelog.txt`. Remove the uninteresting top lines.  You may want to link to the [Zope changelog](https://github.com/zopefoundation/Zope/blob/master/CHANGES.rst) with a specific tag.
  - [x] Create a file `release/RELEASE-NOTES.md`. It may be enough to look through the changelog and copy interesting changes.
  - [x] Get the `versions.cfg` file and any other versions files from coredev.
  - [x] Create a `release/constraints.txt` file from this. The above tox command generates this.  Note: at some point I expect the constraints file to become leading, and we may need to generate a `versions.cfg` file instead.
  - [x] Copy (`rsync`) these files to the pending release directory.  (We used to copy packages as well, but we do not do this for Plone 6 anymore.)
- [x] Write a post on community.plone.org announcing a pending/soft release. See [example](https://community.plone.org/t/plone-6-0-0b3-released/15728).  In the 6.0 alpha/beta/rc stage, we can skip pending releases and just make a real release.
- [x] Wait for feedback, preferably at most a few days.  As said, in the alpha/beta/rc stage, we can skip this.

## Final release, Docker

- [x] Make final release of `Products.CMFPlone` to PyPI, update `versions.cfg`.
- [x] In `release/6.0-dev` branch update changelog, release notes, `constraints.txt`.
- [x] Create tag of the `release/6.0-dev` branch, e.g. 6.0.0a1, and push to GitHub.
- [x] Make final release directory on dist.plone.org, with versions, requirements, constraints, changelog, release notes.
- [x] Update the "-latest" links on dist.plone.org, e.g. `ln -sfT 6.0.0a1 6.0-latest`
- [x] Notify Erico, perhaps on the `#install-and-deploy` Discord channel, that there is a new release.  He can create Docker images then.

## Announcements

You probably want to wait until the Docker images are there, but don't wait long.

- [x] Create release page on https://plone.org/download/releases
- [x] Send mail to Marketing Team so they can prepare announcements.
- [x] Update the https://plone.org/security/hotfixes/ page in the configuration control panel. This is done in the configuration registry: `plone.securitysupport`, `plone.versions`, `plone.activemaintenance`.  You could ask the security team.
- [x] Publish release page on plone.org.
- [x] Update the [release schedule](https://plone.org/download/release-schedule): note the new release, and say when the next release in this series is expected.
- [x] Edit the link on https://plone.org/download.
- [x] Announce on community.plone.org.

**Comment by mauritsvanrees** [comment]
@thet @petschki @erral @tisto 
I want to make a Plone 6.0.1 release. If possible a release candidate tomorrow (Friday), and a final release early next week. Release schedule says we want this in January. :-)

Could each of you make releases where necessary for `plone.staticresources`, `plonetheme.barceloneta`, `plone.app.locales`, `plone.restapi/volto` please? 
I also want to [release 5.2.11](https://github.com/plone/Products.CMFPlone/issues/3717) but it looks like no further releases are necessary there.

@sneridagh Is latest Volto 16.8.1 fine for 6.0.1, or should we wait on some changes? I would usually just paste the latest version number when I write the release notes.

**Comment by erral** [comment]
plone.app.locales = 6.0.10 released

**Comment by sneridagh** [comment]
@mauritsvanrees I'll try to release a 16.9.0 soon-ish, let's see tomorrow. I'll let you know.

**Comment by petschki** [comment]
@mauritsvanrees I'm waiting for `@patternslib/patternslib==9.8.1` which will be released soon (this weekend?) by @thet and release `plone.staticresources==2.0.5` afterwards.

**Comment by petschki** [comment]
@mauritsvanrees note: as Peter Holzer has a new job since last year and cannot actively develop Plone anymore 😢 I'll do the `plonetheme.barceloneta` and `@plone/plonetheme-barceloneta-base` package releases on pypi and npmjs in the future.

/cc @agitator ok with you?

**Comment by mauritsvanrees** [comment]
I will make a 6.0.1 release candidate with the releases that are here now.
There will be another Plone release within one month, so I don't think there is a great need to wait for individual packages.

I am thinking of creating a fixed schedule, like: every fix that is in on the 20th of the month will go into a new Plone bugfix release. Or the third Monday of the month, something like that. Make it clear to everyone, so expectations are clear. After that, it is at the discretion of the release manager, who should of course still be open to suggestions. And I would still do a ping in an issue like this one to get final releases in. Allow three days or so to get individual packages released. Then I create the release candidate.

This is not a critique on anyone. Every package or set of packages has its own dynamic, where for example staticresources depends on the state of mockup and Patternslib, and we need a good combination of plone.restapi, plone.volto and Volto.
It is just so easy for me to get drawn into checking pull requests for individual packages, to make sure every last available fix is in the release and working stably together, resulting in a delay of getting already existing and released fixes out to users. I like to avoid that.
We can discuss in the Innsbruck sprint with the people who are there to see if we can get a rough schedule that works for most.

**Comment by gforcada** [comment]
Calendar planning releases, specially for bugfix ones, i.e. `6.0.x` sounds like a great idea ✨ 

Knowing that if you make a contribution and gets merged, it will be _at most_ a month away from being in an official release is a great way to encourage upstream contributing 👍🏾 

Something like: _From 20th to 25th of each month packages are expected to have package releases, from 25th until the end of the month a Plone release with those package releases is to be expected_

**Comment by thet** [comment]
@mauritsvanrees this idea also sounds great to me! Let's discuss in Innsbruck.
