### ISSUE TITLE
Refactor site creation in Products.CMFPlone to use plone.distribution

### ISSUE THREAD

**Issue by ericof** [plone/Products.CMFPlone#3961]
Part of #3854

# Tasks
- [x] `Products.CMFPlone.browser.admin.AddPloneSite` only registered if `plone.distribution` is not available
- [ ] Refactor site creation to be like the function from plone.distribution (supporting a distribution)
- [x] Remove creation of example content (make sure those are still created in the test layer)

**Comment by mauritsvanrees** [comment]
Without `plone.distribution` available, do we want to remove the Advanced options?  I can imagine that we want to point users to *either* distributions *or* just let them install the extra profiles via the Add-ons control panel.

<img width="851" alt="Screenshot 2024-06-19 at 19 31 45" src="https://github.com/plone/Products.CMFPlone/assets/210587/ac0160ec-4788-4156-ba50-baf2527004fe">

Actually, you can't install "Zope Root Cookie Login" (`Products.PlonePAS:root-cookie` profile) in the control panel.  You would need to do that via `portal_setup`.  But that is really an advanced corner case.   Since it works on the Zope root, you don't even want it available for install from within Plone.  So I think that is fine.  Anyway, you can still do that in a Distribution. :-)

**Comment by mauritsvanrees** [comment]
Progress during Buschenschankensprint (in the train back actually)

* https://github.com/plone/Products.CMFPlone/pull/3981
* https://github.com/plone/plone.app.testing/pull/97

**Comment by mauritsvanrees** [comment]
The CMFPlone PR does not "Refactor site creation to be like the function from plone.distribution (supporting a distribution)".  I don't really know what that would like like if `plone.distribution` is not available, which is the only way that the `plone-addsite` view is even visible.

Ah, or do you mean that the `factory.addPloneSite` function should be able to install a distribution if `plone.distribution` *is* available?  Then this function would accept an extra `distribution` keyword argument, and call a function in `plone.distribution`.  Something like that?

**Comment by mauritsvanrees** [comment]
@ericof @davisagli Can this issue be closed?  Or do we want to do something about my previous comment about the open task "Refactor site creation to be like the function from plone.distribution (supporting a distribution)"?

**Comment by mauritsvanrees** [comment]
Ah, right. In `addPloneSite` you can pass a [`distribution_name`](https://github.com/plone/Products.CMFPlone/pull/3981/files#diff-364fa892973e67343f3a2c29d75de4aa9885dfb4a2735ca5ea88ca7e95fb0b89R141).
