### ISSUE TITLE
Clear out all startup "WARNING plone.behavior Specifing 'for' in behavior 'xxx' if no 'factory' is given has no effect and is superfluous." messages

### ISSUE THREAD

**Issue by fulv** [plone/Products.CMFPlone#669]
When the instance is started, there are a bunch of warnings that should be cleared up in the underlying code.  (Note that "Specifying" is misspelled, too.)

```
2015-07-12 23:09:04 WARNING plone.behavior Specifing 'for' in behavior 'Name from title' if no 'factory' is given has no effect and is superfluous.
2015-07-12 23:09:04 WARNING plone.behavior Specifing 'for' in behavior 'Name from file name' if no 'factory' is given has no effect and is superfluous.
2015-07-12 23:09:04 WARNING plone.behavior Specifing 'for' in behavior 'Navigation root' if no 'factory' is given has no effect and is superfluous.
2015-07-12 23:09:04 WARNING plone.behavior Specifing 'for' in behavior 'Exclude From navigation' if no 'factory' is given has no effect and is superfluous.
2015-07-12 23:09:04 WARNING plone.behavior Specifing 'for' in behavior 'Next previous navigation toggle' if no 'factory' is given has no effect and is superfluous.
2015-07-12 23:09:04 WARNING plone.behavior Specifing 'for' in behavior 'Allow discussion' if no 'factory' is given has no effect and is superfluous.
2015-07-12 23:09:04 WARNING plone.behavior Specifing 'for' in behavior 'Next previous navigation' if no 'factory' is given has no effect and is superfluous.
2015-07-12 23:09:04 WARNING plone.behavior Specifing 'for' in behavior 'Related items' if no 'factory' is given has no effect and is superfluous.
2015-07-12 23:09:04 WARNING plone.behavior Specifing 'for' in behavior 'Event Basic' if no 'factory' is given has no effect and is superfluous.
2015-07-12 23:09:04 WARNING plone.behavior Specifing 'for' in behavior 'Event Recurrence' if no 'factory' is given has no effect and is superfluous.
2015-07-12 23:09:04 WARNING plone.behavior Specifing 'for' in behavior 'Event Location' if no 'factory' is given has no effect and is superfluous.
2015-07-12 23:09:04 WARNING plone.behavior Specifing 'for' in behavior 'Event Attendees' if no 'factory' is given has no effect and is superfluous.
2015-07-12 23:09:04 WARNING plone.behavior Specifing 'for' in behavior 'Event Contact' if no 'factory' is given has no effect and is superfluous.
2015-07-12 23:09:04 WARNING plone.behavior Specifing 'for' in behavior 'Locking' if no 'factory' is given has no effect and is superfluous.
2015-07-12 23:09:04 WARNING plone.behavior Specifing 'for' in behavior 'Table of contents' if no 'factory' is given has no effect and is superfluous.
2015-07-12 23:09:06 WARNING plone.behavior Specifing 'for' in behavior 'Referenceable' if no 'factory' is given has no effect and is superfluous.
2015-07-12 23:09:08 WARNING plone.behavior Specifing 'for' in behavior 'Multilingual Support' if no 'factory' is given has no effect and is superfluous.
```

**Comment by fulv** [comment]
This is an umbrella ticket to coordinate several connected pull requests:

- [ ] plone/plone.app.contenttypes#242
- [ ] plone/buildout.coredev#96
- [ ] plone/plone.app.dexterity#170
- [ ] plone/plone.app.relationfield#14
- [ ] plone/plone.app.event#193
- [ ] plone/plone.app.lockingbehavior#2
- [ ] plone/plone.app.multilingual#171
- [ ] plone/plone.app.referenceablebehavior#5
