### ISSUE TITLE
Several issues with ttw schemaeditor

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#776]
While using it I found 3 major issues filed here:
- [x] plone/plone.schemaeditor#28
- [ ] plone/plone.schemaeditor#29 (feature)
- [x] plone/plone.schemaeditor#30

**Comment by tomgross** [comment]
I put these here since the bugs are regressions from Plone 5.1b3 to Plone 5.1b4 and collective.easyform is ment to work with Plone 5.1. I guess this needs to be fixed in mockup / plone.schemaeditor

- [ ] https://github.com/collective/collective.easyform/issues/82
- [ ] https://github.com/collective/collective.easyform/issues/81

**Comment by thet** [comment]
@tomgross - fixes with https://github.com/plone/plone.schemaeditor/pull/56
please review and merge if all is OK.

**Comment by jensens** [comment]
Since this is a meta report and all major problems are solved, we can close this.
