### ISSUE TITLE
Horizontal toolbar issues

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#957]
- [ ] Personal tools overflow (#946)
- [ ] Missing personal toolbar when expanding the toolbar (#950)
- [ ] More… menu completely misplaced (#952)

**Comment by vangheem** [comment]
We've noticed these problems as well. We ended up going with a toolbar on top and bottom. There is just no way to fit everything you need on the toolbar otherwise.

Here is an example:

![screen shot 2016-05-06 at 9 30 35 am](https://cloud.githubusercontent.com/assets/524413/15076081/6d394c4a-136d-11e6-9e84-ad057dd7772e.png)

Then you also have more room to have breadcrumbs and other things in the toolbar.

**Comment by djay** [comment]
I think that part of the problem here is that plugin authors don't have much options with regard to where to make their items available on the toolbar. Greenbar/toolbar tabs has always been easiest. But from a UX perspective this is not ideal. Not everything is top level and needs to be one click away. For example, in that list Sydication, aliases, Analytics and even history I think wouldn't be used often enough. 
I think we can do a few things

1. Do a vote/survey on what are the top 3-4 things people want to be one click away. Make people priotise. That should give us data to work from. Include end users in that as well.
2. Have a way to easily put more forms into the edit view. For example, aliases could be available from edit, since it is conceptually about working with the url of the content. Syndication might be within edit to. Perhaps within edit > settings there could be a menu of extra settings.
3. Have 1-2 generic dropdowns similar to Actions. The idea of having metadata/history dropdown has been suggested. Analytics might fall under that menu. 
4. I've mentioned before how sharing and state are tightly related and can be combined.

**Comment by rioksane** [comment]
I mostly agree with vanhgheem and djay here. After using Plone 5 in various sites in the last months, I agree that there's room for improvement, even though I do like Plone 5 and its new toolbar very much. Right now I'm working on a site that has 11 links on the toolbar - and they all look as important compared to each other. 
<img width="190" alt="plone5-toolbar-crowded" src="https://cloud.githubusercontent.com/assets/5127672/16976299/9d154f76-4e56-11e6-81f6-e7079b3d581a.png">

It doesn't or shouldn't have to be major changes - just make the most important links bold (Add, Edit, Contents) and put some horizontal lines and/or marging to separate primary and secondary function sets. 
<img width="872" alt="plone5-toolbar-suggestions-part2" src="https://cloud.githubusercontent.com/assets/5127672/16976282/7208a2ec-4e56-11e6-8cd7-3366c1989273.png">

A more radical change could be a new "More..." or "Settings" -menu item that could contain not so frequently used functions such as Rules, Sharing, History and others that come from add ons.

**Comment by omkumar312** [comment]
I want to work on this issues please assign me this issue.

**Comment by jensens** [comment]
Closing as outdated (8 years old). Plone 5 toolbar tracker issue. Toolbar completely rewritten for Plone 6.
If you think this issue is still relevant please reopen it. Thank you for the original report!
